name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest
      env:
        SECRET_KEY: test-secret-key
        FLASK_APP: run.py
        FLASK_ENV: test
        MONGODB_URI: mongodb://localhost:27017
        MONGODB_DB: trello_clone_test
        JWT_SECRET_KEY: test-jwt-secret-key 